INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Andres','Guzman','profesor@bolsadeideas.com','2018-01-01')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Mr Jhon','Perez','jhon@bolsadeideas.com','2019-01-02')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Juan','Lopez','juan@bolsadeideas.com','2017-01-01')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Sara','Jaramillo','sara@bolsadeideas.com','2015-01-11')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Lucia','Villegas','lucia@bolsadeideas.com','2018-01-01')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Maria','Toro','maria@bolsadeideas.com','2018-01-05')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Felipe','Guzman','felipe@bolsadeideas.com','2018-01-03')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Santiago','Lopera','santiago@bolsadeideas.com','2018-01-03')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Juana','Mendez','juana@bolsadeideas.com','2018-01-08')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Lucrecia','Jerez','lucrecia@bolsadeideas.com','2018-01-07')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('David','Lopez','david@bolsadeideas.com','2018-01-06')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Sofia','Ramirez','sofia@bolsadeideas.com','2018-01-05')
INSERT INTO clientes (nombre, apellido, email, create_at ) values ('Ana','Alzate','ana@bolsadeideas.com','2018-01-04')